name: Run tests

on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: Test with Node.js 23 on windows-latest
    timeout-minutes: 15
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false

      - name: Setup Node.js@23
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 23

      - name: Print version information
        run: |
          echo OS: $(node -p "os.version()")
          echo Node.js: $(node --version)
          echo npm: $(npm --version)
          echo git: $(git --version)

      - name: Install dependencies
        run: npm install

      - name: Print installed dependencies
        run: npm ls --all
        continue-on-error: true

      - name: Run tests
        if: steps.coverage.outcome == 'skipped'
        run: npm run test:javascript
        env:
          CI: true
